#!/bin/bash

# function
yes_or_no(){
    echo "Is your name $* ?"
    while true
    do
        echo -n "Enter yes or not: "
        read x
        case "$x" in
            [yY] | [Yy][Ee][Ss] ) return 0;;
            [nN] | [nN][oO] )     return 1;;
            * )                   echo "Please answer yes or no."
        esac
    done
}

# main
echo "Original parameters are $*."

if yes_or_no "$1"
then
    echo "Hi $1, nice name."
else
    echo "Never mind."
fi
exit 0